### ISSUE TITLE
Applying various Image Pre-Processing and Noise Reduction operations to clean the Images in our Dataset.

### ISSUE THREAD

**Issue by ShudhanshuGR8** [upes-open/OSC-Automated-Parking_System#2]
This issue expects a Python working script which takes the Image from Datasets and applies various Pre-Processing algorithms and operations to make Number Plate detection more easy. Examples of a few Pre-Processing steps are Converting image to greyscale and then sharpening the image, detecting contours, etc.

**Comment by snigdha510** [comment]
Please assign me this issue.

**Comment by saarinii** [comment]
I would also like to work on the issue

**Comment by ShudhanshuGR8** [comment]
Okay both of you please do collaborate with each other. Don't worry about the points and leaderboard. Both of you will recieve equal points upon the completion of the task. 
Best of luck and Have fun collaborating with each other.

**Comment by saarinii** [comment]
yeah sure, I would love to @snigdha510
