### ISSUE TITLE
A Registration Form where the User will enter the License Plate Number and then storing that in a Database

### ISSUE THREAD

**Issue by ShudhanshuGR8** [upes-open/OSC-Automated-Parking_System#6]
This issue is also part of web/mobile Application Development. This is to appear the First time the user logins into our Application and collects the Data regarding his Personal Information and his Vehicle's License Plate Number. This is done in order to match the Detected Number Plate and generate a Parking token containing where to park as well.

**Comment by smriti243** [comment]
I am working on it.
